name: CI

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Display environment variables
        run: |
          echo DOCKER_USERNAME=$DOCKER_USERNAME
          echo DOCKER_PASSWORD=$DOCKER_PASSWORD
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        run: |
          docker build -t rlsbezerra/ci-cd:1.0.0 app/.
          docker push rlsbezerra/ci-cd:1.0.0
