name: CI

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker CLI
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and push image
        run: |
          docker build -t rlsbezerra/ci-cd:1.0.0 app/.
          docker push rlsbezerra/ci-cd:1.0.0
